version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/front
      args:
        VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
        VITE_BASE_URL: ${VITE_BASE_URL}
      dockerfile: dockerfile
    ports:
      - "443:443"
    depends_on:
      - backend
    environment:
      - VITE_GEMINI_API_KEY=AIzaSyAA0oWvCDjM6PlDOJLlrqyc0J-6FdWUcTo
      - VITE_BASE_URL=https://node70.cs.colman.ac.il:4000/

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - DB_CONNECT=mongodb://server:123123123@10.10.246.70:21771/web_class
      - TOKEN_SECRET=4eee4852695b0e1722b0bd9ba6c87758205a2e98b1e46b08610706d63873c6016f2bd9f3e5a0c0cf5bbefd2cecad58b95185319d57e8fd7efd2c142333e09772
      - TOKEN_EXPIRATION=3d
      - REFRESH_TOKEN_EXPIRATION=7d
      - GOOGLE_CLIENT_ID=1037634719253-s17gvuugf38vbjq2vak8vfibqqmk8gqb.apps.googleusercontent.com
      - BASE_URL=https://node70.cs.colman.ac.il:4000/