
POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "New post",
    "senderID": "331",
    "content": "Test"
}

###

GET http://localhost:3000/post

###

GET http://localhost:3000/post/67471fa41368898cd3f6ca0e


###

GET http://localhost:3000/post?sender=333

###
PUT http://localhost:3000/post/67471fa41368898cd3f6ca0e
Content-Type: application/json

{
    "title": "Updated again!",
    "content": "Updated content!!"
}

###

POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "67471f9b1368898cd3f6ca0c",  
  "sender": "Ilana Belokon",
  "content": "Great post! I really enjoyed reading it."
}

###

PUT http://localhost:3000/comments/675066550be685c196ef9460
Content-Type: application/json

{
  "content": "Good job"
}

###

GET http://localhost:3000/comments?postId=67471f9b1368898cd3f6ca0c

###

GET http://localhost:3000/comments/675066550be685c196ef9460

###

DELETE http://localhost:3000/comments/6750605d5be7df859450d23c 

###

POST http://localhost:3000/users Content-Type: application/json

{
"username": "Ilana", "email": "ilana@gmail.com", "password": "ilana"
}

###

PUT http://localhost:3000/users/67507f6df8656133a81c750a Content-Type: application/json

{
"email": "new@gmail.com"
}

###

GET http://localhost:3000/users

###

GET http://localhost:3000/comments?userId=67507f6df8656133a81c750a

###

DELETE http://localhost:3000/users/67507f6df8656133a81c750a

