
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "New post",
    "owner": "Dana",
    "content": "Test"
}

###

GET http://localhost:3000/posts/6744dba9d21f91924e640d50

###

POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "6744c75ed8a5d2e3225d9539",  
  "sender": "Ilana Belokon",
  "content": "Great post! I really enjoyed reading it."
}

