### Posts API

# Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "New post",
    "sender": "3311111111",
    "content": "Test"
}

###

# Get all posts
GET http://localhost:3000/posts

###

# Get a post by ID
GET http://localhost:3000/posts/67471fa41368898cd3f6ca0e

###

# Get posts by sender ID
GET http://localhost:3000/posts?sender=3311111111

###

# Delete a post by ID
DELETE http://localhost:3000/posts/67471f9b1368898cd3f6ca0c

###

### Comments API

# Create a new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "post": "67471fa41368898cd3f6ca0e",
    "content": "This is a comment",
    "sender": "user123"
}

###

# Get all comments
GET http://localhost:3000/comments

###

# Get all comments for a post
GET http://localhost:3000/comments?post=67471f9b1368898cd3f6ca0c

###

# Get a comment by ID
GET http://localhost:3000/comments/6744dbb5d21f91924e640d53

###

# Delete a comment by ID
DELETE http://localhost:3000/comments/6744dbb5d21f91924e640d53

###